a="py th"
print(a.capitalize())
print(a.center(24),'*')
print(a.casefold())
print(a.count("py"))
print(a.endswith("ome"))
print(a.encode())
print(a.find("py"))
print(a.index("py"))
print("jhygyh3".isalnum())

print("5".isdigit())
print("Ausgyyda".islower())
print(a.join("erfdre"))
print("    ".isspace())
print(a.ljust(50))
print(ord("k"))
print(chr(109))
print(bool("hjfby"))
print(all(a))
